replicaCount: 1

image:
  repository: cuong111111/web
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30002

ingress:
  enabled: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
